server:
  port: 8083

spring:
  application:
    name: notifier-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifier-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ghostfollow.processor_service.model.FollowerChangeEvent

  mail:
    host: smtp.gmail.com
    port: 587
    username: ghostfollowapp@gmail.com
    password: qail dkth arua qgkv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
